version: '3'
services:
  nginx:
    build:
      context: ./docker/nginx/
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - php-fpm
    networks:
      - frontend
      - backend
  php-fpm:
    build:
      context: ./docker/php-fpm/
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - backend
  mysql:
    build:
      context: ./docker/mysql
    ports:
      - "33060:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: ecommerce
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - backend
networks:
  backend:
  frontend:
